# Generated by Django 6.0.5 on 2026-05-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('disease', models.CharField(blank=True, max_length=100)),
                ('pesticide', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
